ja:
  activerecord:
    models:
      feed: フィード
      blog: ブログ
      user: ユーザー
    attributes:
      feed:
        image: 写真
        content: 内容
      blog:
        title: タイトル
        content: 内容
      user:
        title: タイトル
        name: 名前
        email: メールアドレス
        current_password: 現在のパスワード
        password: パスワード
        password_confirmation: 確認用パスワード
        remember_me: ログインを記憶
        image: プロフィール
